import type { Metadata } from 'next'
import './globals.css'
import '@mysten/dapp-kit/dist/index.css'
import Providers from '@/components/Providers'
import TopNav from '@/components/navbar/TopNavGlass'
import { auth } from '@/auth'

export const metadata: Metadata = {
  title: 'Match Me',
  description: 'Generated by create next app',
}

const {
  NEXT_PUBLIC_ENOKI_KEY = '',
  GOOGLE_CLIENT_ID = '',
  SUI_NETWORK = 'testnet',
} = process.env

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  const userId = session?.user?.id || null
  const profileComplete = session?.user.profileComplete as boolean
  return (
    <html lang="en">
      <body>
        <Providers
          enokiApiKey={NEXT_PUBLIC_ENOKI_KEY}
          googleClientId={GOOGLE_CLIENT_ID}
          suiNetwork={SUI_NETWORK as 'mainnet' | 'testnet'}
          profileComplete={profileComplete}
          userId={userId}
        >
          <TopNav />
          <main className="container mx-auto">{children}</main>
        </Providers>
      </body>
    </html>
  )
}
