import type { Metadata } from 'next'
import './globals.css'
import '@mysten/dapp-kit/dist/index.css'
import Providers from '@/components/Providers'
import TopNavGlassWrapper from '@/components/navbar/TopNavGlassWrapper'
import { auth } from '@/auth'

// export const metadata: Metadata = {
//   title: 'Match Me',
//   description: 'Generated by create next app',
// }

const {
  NEXT_PUBLIC_ENOKI_KEY = '',
  GOOGLE_CLIENT_ID = '',
  SUI_NETWORK = 'testnet',
  NEXT_PUBLIC_BASE_URL = 'http://localhost:3000',
} = process.env

export async function generateMetadata(): Promise<Metadata> {
  const URL = process.env.NEXT_PUBLIC_BASE_URL;
  return {
    title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
    description:
      "Generated by `create-onchain --mini`, a Next.js template for MiniKit",
    other: {
      "fc:frame": JSON.stringify({
        version: "next",
        imageUrl: process.env.NEXT_PUBLIC_APP_HERO_IMAGE,
        button: {
          title: `Launch ${process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME}`,
          action: {
            type: "launch_frame",
            name: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
            url: process.env.NEXT_PUBLIC_BASE_URL,
            splashImageUrl: process.env.NEXT_PUBLIC_SPLASH_IMAGE,
            splashBackgroundColor:
              process.env.NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR,
          },
        },
      }),
    },
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  const userId = session?.user?.id || null
  const profileComplete = session?.user.profileComplete as boolean
  return (
    <html lang="en">
      <body>
        <Providers
          enokiApiKey={NEXT_PUBLIC_ENOKI_KEY}
          googleClientId={GOOGLE_CLIENT_ID}
          redirectUrl={NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'}
          suiNetwork={SUI_NETWORK as 'mainnet' | 'testnet'}
          profileComplete={profileComplete}
          userId={userId}
        >
          <TopNavGlassWrapper />
          <main className="container mx-auto pt-6">{children}</main>
        </Providers>
      </body>
    </html>
  )
}
