[package]
name = "matching_me"
edition = "2024.beta"
license = "MIT"
authors = ["Maverick Trinh, Alvin Nguyen"]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]

[addresses]
matching_me = "0x0"

[dev-dependencies]

[dev-addresses]

